/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfilecopyRouteImport } from './routes/user/profile copy'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteAccountRouteImport } from './routes/auth/complete-account'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminClientsClient_idRouteImport } from './routes/admin/clients/$client_id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfilecopyRoute = UserProfilecopyRouteImport.update({
  id: '/user/profile copy',
  path: '/user/profile copy',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/auth/complete-account',
  path: '/auth/complete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsClient_idRoute = AdminClientsClient_idRouteImport.update({
  id: '/clients/$client_id',
  path: '/clients/$client_id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/user/profile': typeof UserProfileRoute
  '/user/profile copy': typeof UserProfilecopyRoute
  '/admin/clients/$client_id': typeof AdminClientsClient_idRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/user/profile': typeof UserProfileRoute
  '/user/profile copy': typeof UserProfilecopyRoute
  '/admin/clients/$client_id': typeof AdminClientsClient_idRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/user/profile': typeof UserProfileRoute
  '/user/profile copy': typeof UserProfilecopyRoute
  '/admin/clients/$client_id': typeof AdminClientsClient_idRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/user/profile'
    | '/user/profile copy'
    | '/admin/clients/$client_id'
    | '/admin/clients/'
    | '/admin/projects/'
    | '/admin/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/user/profile'
    | '/user/profile copy'
    | '/admin/clients/$client_id'
    | '/admin/clients'
    | '/admin/projects'
    | '/admin/team'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/user/profile'
    | '/user/profile copy'
    | '/admin/clients/$client_id'
    | '/admin/clients/'
    | '/admin/projects/'
    | '/admin/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSigninRoute: typeof AuthSigninRoute
  UserProfileRoute: typeof UserProfileRoute
  UserProfilecopyRoute: typeof UserProfilecopyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile copy': {
      id: '/user/profile copy'
      path: '/user/profile copy'
      fullPath: '/user/profile copy'
      preLoaderRoute: typeof UserProfilecopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-account': {
      id: '/auth/complete-account'
      path: '/auth/complete-account'
      fullPath: '/auth/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/team'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$client_id': {
      id: '/admin/clients/$client_id'
      path: '/clients/$client_id'
      fullPath: '/admin/clients/$client_id'
      preLoaderRoute: typeof AdminClientsClient_idRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminClientsClient_idRoute: typeof AdminClientsClient_idRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminClientsClient_idRoute: AdminClientsClient_idRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSigninRoute: AuthSigninRoute,
  UserProfileRoute: UserProfileRoute,
  UserProfilecopyRoute: UserProfilecopyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
