/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteAccountRouteImport } from './routes/auth/complete-account'
import { Route as PrivateWorkspaceRouteImport } from './routes/_private/workspace'
import { Route as PrivateTeamRouteImport } from './routes/_private/team'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PrivateProjectsRouteImport } from './routes/_private/projects'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateLibraryRouteImport } from './routes/_private/library'
import { Route as PrivateFinancesRouteImport } from './routes/_private/finances'
import { Route as PrivateWorkspaceIndexRouteImport } from './routes/_private/workspace/index'
import { Route as PrivateLibraryIndexRouteImport } from './routes/_private/library/index'
import { Route as PrivateCompaniesIndexRouteImport } from './routes/_private/companies/index'
import { Route as PrivateWorkspaceScheduleRouteImport } from './routes/_private/workspace/schedule'
import { Route as PrivateWorkspaceHistoryRouteImport } from './routes/_private/workspace/history'
import { Route as PrivateWorkspaceClientsRouteImport } from './routes/_private/workspace/clients'
import { Route as PrivateLibraryGuideIdRouteImport } from './routes/_private/library/$guideId'
import { Route as PrivateCompaniesCompany_idRouteImport } from './routes/_private/companies/$company_id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/auth/complete-account',
  path: '/auth/complete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateWorkspaceRoute = PrivateWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateTeamRoute = PrivateTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProjectsRoute = PrivateProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateLibraryRoute = PrivateLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateFinancesRoute = PrivateFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateWorkspaceIndexRoute = PrivateWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateWorkspaceRoute,
} as any)
const PrivateLibraryIndexRoute = PrivateLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLibraryRoute,
} as any)
const PrivateCompaniesIndexRoute = PrivateCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateWorkspaceScheduleRoute =
  PrivateWorkspaceScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => PrivateWorkspaceRoute,
  } as any)
const PrivateWorkspaceHistoryRoute = PrivateWorkspaceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PrivateWorkspaceRoute,
} as any)
const PrivateWorkspaceClientsRoute = PrivateWorkspaceClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PrivateWorkspaceRoute,
} as any)
const PrivateLibraryGuideIdRoute = PrivateLibraryGuideIdRouteImport.update({
  id: '/$guideId',
  path: '/$guideId',
  getParentRoute: () => PrivateLibraryRoute,
} as any)
const PrivateCompaniesCompany_idRoute =
  PrivateCompaniesCompany_idRouteImport.update({
    id: '/companies/$company_id',
    path: '/companies/$company_id',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/finances': typeof PrivateFinancesRoute
  '/library': typeof PrivateLibraryRouteWithChildren
  '/profile': typeof PrivateProfileRoute
  '/projects': typeof PrivateProjectsRoute
  '/settings': typeof PrivateSettingsRoute
  '/team': typeof PrivateTeamRoute
  '/workspace': typeof PrivateWorkspaceRouteWithChildren
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/companies/$company_id': typeof PrivateCompaniesCompany_idRoute
  '/library/$guideId': typeof PrivateLibraryGuideIdRoute
  '/workspace/clients': typeof PrivateWorkspaceClientsRoute
  '/workspace/history': typeof PrivateWorkspaceHistoryRoute
  '/workspace/schedule': typeof PrivateWorkspaceScheduleRoute
  '/companies/': typeof PrivateCompaniesIndexRoute
  '/library/': typeof PrivateLibraryIndexRoute
  '/workspace/': typeof PrivateWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof UnauthorizedRoute
  '/finances': typeof PrivateFinancesRoute
  '/profile': typeof PrivateProfileRoute
  '/projects': typeof PrivateProjectsRoute
  '/settings': typeof PrivateSettingsRoute
  '/team': typeof PrivateTeamRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/': typeof PrivateIndexRoute
  '/companies/$company_id': typeof PrivateCompaniesCompany_idRoute
  '/library/$guideId': typeof PrivateLibraryGuideIdRoute
  '/workspace/clients': typeof PrivateWorkspaceClientsRoute
  '/workspace/history': typeof PrivateWorkspaceHistoryRoute
  '/workspace/schedule': typeof PrivateWorkspaceScheduleRoute
  '/companies': typeof PrivateCompaniesIndexRoute
  '/library': typeof PrivateLibraryIndexRoute
  '/workspace': typeof PrivateWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_private/finances': typeof PrivateFinancesRoute
  '/_private/library': typeof PrivateLibraryRouteWithChildren
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/projects': typeof PrivateProjectsRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_private/team': typeof PrivateTeamRoute
  '/_private/workspace': typeof PrivateWorkspaceRouteWithChildren
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/companies/$company_id': typeof PrivateCompaniesCompany_idRoute
  '/_private/library/$guideId': typeof PrivateLibraryGuideIdRoute
  '/_private/workspace/clients': typeof PrivateWorkspaceClientsRoute
  '/_private/workspace/history': typeof PrivateWorkspaceHistoryRoute
  '/_private/workspace/schedule': typeof PrivateWorkspaceScheduleRoute
  '/_private/companies/': typeof PrivateCompaniesIndexRoute
  '/_private/library/': typeof PrivateLibraryIndexRoute
  '/_private/workspace/': typeof PrivateWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/finances'
    | '/library'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/companies/$company_id'
    | '/library/$guideId'
    | '/workspace/clients'
    | '/workspace/history'
    | '/workspace/schedule'
    | '/companies/'
    | '/library/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/finances'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/team'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/'
    | '/companies/$company_id'
    | '/library/$guideId'
    | '/workspace/clients'
    | '/workspace/history'
    | '/workspace/schedule'
    | '/companies'
    | '/library'
    | '/workspace'
  id:
    | '__root__'
    | '/_private'
    | '/unauthorized'
    | '/_private/finances'
    | '/_private/library'
    | '/_private/profile'
    | '/_private/projects'
    | '/_private/settings'
    | '/_private/team'
    | '/_private/workspace'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/_private/'
    | '/_private/companies/$company_id'
    | '/_private/library/$guideId'
    | '/_private/workspace/clients'
    | '/_private/workspace/history'
    | '/_private/workspace/schedule'
    | '/_private/companies/'
    | '/_private/library/'
    | '/_private/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSigninRoute: typeof AuthSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-account': {
      id: '/auth/complete-account'
      path: '/auth/complete-account'
      fullPath: '/auth/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/workspace': {
      id: '/_private/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof PrivateWorkspaceRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/team': {
      id: '/_private/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PrivateTeamRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/projects': {
      id: '/_private/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PrivateProjectsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/library': {
      id: '/_private/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof PrivateLibraryRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/finances': {
      id: '/_private/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof PrivateFinancesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/workspace/': {
      id: '/_private/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof PrivateWorkspaceIndexRouteImport
      parentRoute: typeof PrivateWorkspaceRoute
    }
    '/_private/library/': {
      id: '/_private/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof PrivateLibraryIndexRouteImport
      parentRoute: typeof PrivateLibraryRoute
    }
    '/_private/companies/': {
      id: '/_private/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof PrivateCompaniesIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/workspace/schedule': {
      id: '/_private/workspace/schedule'
      path: '/schedule'
      fullPath: '/workspace/schedule'
      preLoaderRoute: typeof PrivateWorkspaceScheduleRouteImport
      parentRoute: typeof PrivateWorkspaceRoute
    }
    '/_private/workspace/history': {
      id: '/_private/workspace/history'
      path: '/history'
      fullPath: '/workspace/history'
      preLoaderRoute: typeof PrivateWorkspaceHistoryRouteImport
      parentRoute: typeof PrivateWorkspaceRoute
    }
    '/_private/workspace/clients': {
      id: '/_private/workspace/clients'
      path: '/clients'
      fullPath: '/workspace/clients'
      preLoaderRoute: typeof PrivateWorkspaceClientsRouteImport
      parentRoute: typeof PrivateWorkspaceRoute
    }
    '/_private/library/$guideId': {
      id: '/_private/library/$guideId'
      path: '/$guideId'
      fullPath: '/library/$guideId'
      preLoaderRoute: typeof PrivateLibraryGuideIdRouteImport
      parentRoute: typeof PrivateLibraryRoute
    }
    '/_private/companies/$company_id': {
      id: '/_private/companies/$company_id'
      path: '/companies/$company_id'
      fullPath: '/companies/$company_id'
      preLoaderRoute: typeof PrivateCompaniesCompany_idRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateLibraryRouteChildren {
  PrivateLibraryGuideIdRoute: typeof PrivateLibraryGuideIdRoute
  PrivateLibraryIndexRoute: typeof PrivateLibraryIndexRoute
}

const PrivateLibraryRouteChildren: PrivateLibraryRouteChildren = {
  PrivateLibraryGuideIdRoute: PrivateLibraryGuideIdRoute,
  PrivateLibraryIndexRoute: PrivateLibraryIndexRoute,
}

const PrivateLibraryRouteWithChildren = PrivateLibraryRoute._addFileChildren(
  PrivateLibraryRouteChildren,
)

interface PrivateWorkspaceRouteChildren {
  PrivateWorkspaceClientsRoute: typeof PrivateWorkspaceClientsRoute
  PrivateWorkspaceHistoryRoute: typeof PrivateWorkspaceHistoryRoute
  PrivateWorkspaceScheduleRoute: typeof PrivateWorkspaceScheduleRoute
  PrivateWorkspaceIndexRoute: typeof PrivateWorkspaceIndexRoute
}

const PrivateWorkspaceRouteChildren: PrivateWorkspaceRouteChildren = {
  PrivateWorkspaceClientsRoute: PrivateWorkspaceClientsRoute,
  PrivateWorkspaceHistoryRoute: PrivateWorkspaceHistoryRoute,
  PrivateWorkspaceScheduleRoute: PrivateWorkspaceScheduleRoute,
  PrivateWorkspaceIndexRoute: PrivateWorkspaceIndexRoute,
}

const PrivateWorkspaceRouteWithChildren =
  PrivateWorkspaceRoute._addFileChildren(PrivateWorkspaceRouteChildren)

interface PrivateRouteChildren {
  PrivateFinancesRoute: typeof PrivateFinancesRoute
  PrivateLibraryRoute: typeof PrivateLibraryRouteWithChildren
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateProjectsRoute: typeof PrivateProjectsRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateTeamRoute: typeof PrivateTeamRoute
  PrivateWorkspaceRoute: typeof PrivateWorkspaceRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateCompaniesCompany_idRoute: typeof PrivateCompaniesCompany_idRoute
  PrivateCompaniesIndexRoute: typeof PrivateCompaniesIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateFinancesRoute: PrivateFinancesRoute,
  PrivateLibraryRoute: PrivateLibraryRouteWithChildren,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateProjectsRoute: PrivateProjectsRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateTeamRoute: PrivateTeamRoute,
  PrivateWorkspaceRoute: PrivateWorkspaceRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateCompaniesCompany_idRoute: PrivateCompaniesCompany_idRoute,
  PrivateCompaniesIndexRoute: PrivateCompaniesIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSigninRoute: AuthSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
