/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserMycompanyRouteImport } from './routes/user/mycompany'
import { Route as GGuideIdRouteImport } from './routes/g/$guideId'
import { Route as CompanyCompanyIdRouteImport } from './routes/company/$companyId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteAccountRouteImport } from './routes/auth/complete-account'
import { Route as CompanyCompanyIdIndexRouteImport } from './routes/company/$companyId/index'
import { Route as CompanyCompanyIdTeamRouteImport } from './routes/company/$companyId/team'
import { Route as CompanyCompanyIdScheduleRouteImport } from './routes/company/$companyId/schedule'
import { Route as CompanyCompanyIdCrmRouteImport } from './routes/company/$companyId/crm'
import { Route as CompanyCompanyIdAdAccountsRouteImport } from './routes/company/$companyId/ad-accounts'
import { Route as CompanyCompanyIdLibraryIndexRouteImport } from './routes/company/$companyId/library/index'
import { Route as CompanyCompanyIdLibraryGuideIdRouteImport } from './routes/company/$companyId/library/$guideId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserMycompanyRoute = UserMycompanyRouteImport.update({
  id: '/user/mycompany',
  path: '/user/mycompany',
  getParentRoute: () => rootRouteImport,
} as any)
const GGuideIdRoute = GGuideIdRouteImport.update({
  id: '/g/$guideId',
  path: '/g/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/auth/complete-account',
  path: '/auth/complete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdIndexRoute = CompanyCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyCompanyIdRoute,
} as any)
const CompanyCompanyIdTeamRoute = CompanyCompanyIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CompanyCompanyIdRoute,
} as any)
const CompanyCompanyIdScheduleRoute =
  CompanyCompanyIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)
const CompanyCompanyIdCrmRoute = CompanyCompanyIdCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CompanyCompanyIdRoute,
} as any)
const CompanyCompanyIdAdAccountsRoute =
  CompanyCompanyIdAdAccountsRouteImport.update({
    id: '/ad-accounts',
    path: '/ad-accounts',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)
const CompanyCompanyIdLibraryIndexRoute =
  CompanyCompanyIdLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)
const CompanyCompanyIdLibraryGuideIdRoute =
  CompanyCompanyIdLibraryGuideIdRouteImport.update({
    id: '/library/$guideId',
    path: '/library/$guideId',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/g/$guideId': typeof GGuideIdRoute
  '/user/mycompany': typeof UserMycompanyRoute
  '/user/profile': typeof UserProfileRoute
  '/company/$companyId/ad-accounts': typeof CompanyCompanyIdAdAccountsRoute
  '/company/$companyId/crm': typeof CompanyCompanyIdCrmRoute
  '/company/$companyId/schedule': typeof CompanyCompanyIdScheduleRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/company/$companyId/': typeof CompanyCompanyIdIndexRoute
  '/company/$companyId/library/$guideId': typeof CompanyCompanyIdLibraryGuideIdRoute
  '/company/$companyId/library/': typeof CompanyCompanyIdLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/g/$guideId': typeof GGuideIdRoute
  '/user/mycompany': typeof UserMycompanyRoute
  '/user/profile': typeof UserProfileRoute
  '/company/$companyId/ad-accounts': typeof CompanyCompanyIdAdAccountsRoute
  '/company/$companyId/crm': typeof CompanyCompanyIdCrmRoute
  '/company/$companyId/schedule': typeof CompanyCompanyIdScheduleRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/company/$companyId': typeof CompanyCompanyIdIndexRoute
  '/company/$companyId/library/$guideId': typeof CompanyCompanyIdLibraryGuideIdRoute
  '/company/$companyId/library': typeof CompanyCompanyIdLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/g/$guideId': typeof GGuideIdRoute
  '/user/mycompany': typeof UserMycompanyRoute
  '/user/profile': typeof UserProfileRoute
  '/company/$companyId/ad-accounts': typeof CompanyCompanyIdAdAccountsRoute
  '/company/$companyId/crm': typeof CompanyCompanyIdCrmRoute
  '/company/$companyId/schedule': typeof CompanyCompanyIdScheduleRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/company/$companyId/': typeof CompanyCompanyIdIndexRoute
  '/company/$companyId/library/$guideId': typeof CompanyCompanyIdLibraryGuideIdRoute
  '/company/$companyId/library/': typeof CompanyCompanyIdLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/company/$companyId'
    | '/g/$guideId'
    | '/user/mycompany'
    | '/user/profile'
    | '/company/$companyId/ad-accounts'
    | '/company/$companyId/crm'
    | '/company/$companyId/schedule'
    | '/company/$companyId/team'
    | '/company/$companyId/'
    | '/company/$companyId/library/$guideId'
    | '/company/$companyId/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/g/$guideId'
    | '/user/mycompany'
    | '/user/profile'
    | '/company/$companyId/ad-accounts'
    | '/company/$companyId/crm'
    | '/company/$companyId/schedule'
    | '/company/$companyId/team'
    | '/company/$companyId'
    | '/company/$companyId/library/$guideId'
    | '/company/$companyId/library'
  id:
    | '__root__'
    | '/'
    | '/unauthorized'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/company/$companyId'
    | '/g/$guideId'
    | '/user/mycompany'
    | '/user/profile'
    | '/company/$companyId/ad-accounts'
    | '/company/$companyId/crm'
    | '/company/$companyId/schedule'
    | '/company/$companyId/team'
    | '/company/$companyId/'
    | '/company/$companyId/library/$guideId'
    | '/company/$companyId/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSigninRoute: typeof AuthSigninRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRouteWithChildren
  GGuideIdRoute: typeof GGuideIdRoute
  UserMycompanyRoute: typeof UserMycompanyRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/mycompany': {
      id: '/user/mycompany'
      path: '/user/mycompany'
      fullPath: '/user/mycompany'
      preLoaderRoute: typeof UserMycompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$guideId': {
      id: '/g/$guideId'
      path: '/g/$guideId'
      fullPath: '/g/$guideId'
      preLoaderRoute: typeof GGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-account': {
      id: '/auth/complete-account'
      path: '/auth/complete-account'
      fullPath: '/auth/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId/': {
      id: '/company/$companyId/'
      path: '/'
      fullPath: '/company/$companyId/'
      preLoaderRoute: typeof CompanyCompanyIdIndexRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/team': {
      id: '/company/$companyId/team'
      path: '/team'
      fullPath: '/company/$companyId/team'
      preLoaderRoute: typeof CompanyCompanyIdTeamRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/schedule': {
      id: '/company/$companyId/schedule'
      path: '/schedule'
      fullPath: '/company/$companyId/schedule'
      preLoaderRoute: typeof CompanyCompanyIdScheduleRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/crm': {
      id: '/company/$companyId/crm'
      path: '/crm'
      fullPath: '/company/$companyId/crm'
      preLoaderRoute: typeof CompanyCompanyIdCrmRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/ad-accounts': {
      id: '/company/$companyId/ad-accounts'
      path: '/ad-accounts'
      fullPath: '/company/$companyId/ad-accounts'
      preLoaderRoute: typeof CompanyCompanyIdAdAccountsRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/library/': {
      id: '/company/$companyId/library/'
      path: '/library'
      fullPath: '/company/$companyId/library/'
      preLoaderRoute: typeof CompanyCompanyIdLibraryIndexRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/library/$guideId': {
      id: '/company/$companyId/library/$guideId'
      path: '/library/$guideId'
      fullPath: '/company/$companyId/library/$guideId'
      preLoaderRoute: typeof CompanyCompanyIdLibraryGuideIdRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
  }
}

interface CompanyCompanyIdRouteChildren {
  CompanyCompanyIdAdAccountsRoute: typeof CompanyCompanyIdAdAccountsRoute
  CompanyCompanyIdCrmRoute: typeof CompanyCompanyIdCrmRoute
  CompanyCompanyIdScheduleRoute: typeof CompanyCompanyIdScheduleRoute
  CompanyCompanyIdTeamRoute: typeof CompanyCompanyIdTeamRoute
  CompanyCompanyIdIndexRoute: typeof CompanyCompanyIdIndexRoute
  CompanyCompanyIdLibraryGuideIdRoute: typeof CompanyCompanyIdLibraryGuideIdRoute
  CompanyCompanyIdLibraryIndexRoute: typeof CompanyCompanyIdLibraryIndexRoute
}

const CompanyCompanyIdRouteChildren: CompanyCompanyIdRouteChildren = {
  CompanyCompanyIdAdAccountsRoute: CompanyCompanyIdAdAccountsRoute,
  CompanyCompanyIdCrmRoute: CompanyCompanyIdCrmRoute,
  CompanyCompanyIdScheduleRoute: CompanyCompanyIdScheduleRoute,
  CompanyCompanyIdTeamRoute: CompanyCompanyIdTeamRoute,
  CompanyCompanyIdIndexRoute: CompanyCompanyIdIndexRoute,
  CompanyCompanyIdLibraryGuideIdRoute: CompanyCompanyIdLibraryGuideIdRoute,
  CompanyCompanyIdLibraryIndexRoute: CompanyCompanyIdLibraryIndexRoute,
}

const CompanyCompanyIdRouteWithChildren =
  CompanyCompanyIdRoute._addFileChildren(CompanyCompanyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSigninRoute: AuthSigninRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRouteWithChildren,
  GGuideIdRoute: GGuideIdRoute,
  UserMycompanyRoute: UserMycompanyRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
