steps:
  # Instala as dependências
  - name: "node:22"
    entrypoint: npm
    args: ["ci"]

  # Compila o projeto (caso utilize TypeScript)
  - name: "node:22"
    entrypoint: npm
    args: ["run", "build"]

  # Instala o Firebase CLI
  - name: "node:22"
    entrypoint: npm
    args: ["install", "-g", "firebase-tools"]

  # Faz o deploy das Cloud Functions
  - name: "node:22"
    entrypoint: firebase
    args:
      - "deploy"
      - "--only"
      - "functions"
      - "--project=${PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"