/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteAccountRouteImport } from './routes/auth/complete-account'
import { Route as AppUserRouteImport } from './routes/app/user'
import { Route as AppUnauthorizedRouteImport } from './routes/app/unauthorized'
import { Route as AppOrganizationRouteImport } from './routes/app/organization'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppUserProfileRouteImport } from './routes/app/user/profile'
import { Route as AppAdminDashboardRouteImport } from './routes/app/admin/dashboard'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app/admin/users/index'
import { Route as AppAdminClientsIndexRouteImport } from './routes/app/admin/clients/index'
import { Route as AppAdminClientsClient_idRouteImport } from './routes/app/admin/clients/$client_id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/auth/complete-account',
  path: '/auth/complete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppUserProfileRoute = AppUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppUserRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminClientsIndexRoute = AppAdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminClientsClient_idRoute =
  AppAdminClientsClient_idRouteImport.update({
    id: '/clients/$client_id',
    path: '/clients/$client_id',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/organization': typeof AppOrganizationRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/user': typeof AppUserRouteWithChildren
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/user/profile': typeof AppUserProfileRoute
  '/app/admin/clients/$client_id': typeof AppAdminClientsClient_idRoute
  '/app/admin/clients/': typeof AppAdminClientsIndexRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/organization': typeof AppOrganizationRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/user': typeof AppUserRouteWithChildren
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/app': typeof AppIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/user/profile': typeof AppUserProfileRoute
  '/app/admin/clients/$client_id': typeof AppAdminClientsClient_idRoute
  '/app/admin/clients': typeof AppAdminClientsIndexRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/organization': typeof AppOrganizationRoute
  '/app/unauthorized': typeof AppUnauthorizedRoute
  '/app/user': typeof AppUserRouteWithChildren
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/user/profile': typeof AppUserProfileRoute
  '/app/admin/clients/$client_id': typeof AppAdminClientsClient_idRoute
  '/app/admin/clients/': typeof AppAdminClientsIndexRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/admin'
    | '/app/organization'
    | '/app/unauthorized'
    | '/app/user'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/app/'
    | '/app/admin/dashboard'
    | '/app/user/profile'
    | '/app/admin/clients/$client_id'
    | '/app/admin/clients/'
    | '/app/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/admin'
    | '/app/organization'
    | '/app/unauthorized'
    | '/app/user'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/app'
    | '/app/admin/dashboard'
    | '/app/user/profile'
    | '/app/admin/clients/$client_id'
    | '/app/admin/clients'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/app'
    | '/app/admin'
    | '/app/organization'
    | '/app/unauthorized'
    | '/app/user'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/app/'
    | '/app/admin/dashboard'
    | '/app/user/profile'
    | '/app/admin/clients/$client_id'
    | '/app/admin/clients/'
    | '/app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSigninRoute: typeof AuthSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-account': {
      id: '/auth/complete-account'
      path: '/auth/complete-account'
      fullPath: '/auth/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/user': {
      id: '/app/user'
      path: '/user'
      fullPath: '/app/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unauthorized': {
      id: '/app/unauthorized'
      path: '/unauthorized'
      fullPath: '/app/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user/profile': {
      id: '/app/user/profile'
      path: '/profile'
      fullPath: '/app/user/profile'
      preLoaderRoute: typeof AppUserProfileRouteImport
      parentRoute: typeof AppUserRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/users'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/clients/': {
      id: '/app/admin/clients/'
      path: '/clients'
      fullPath: '/app/admin/clients/'
      preLoaderRoute: typeof AppAdminClientsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/clients/$client_id': {
      id: '/app/admin/clients/$client_id'
      path: '/clients/$client_id'
      fullPath: '/app/admin/clients/$client_id'
      preLoaderRoute: typeof AppAdminClientsClient_idRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminClientsClient_idRoute: typeof AppAdminClientsClient_idRoute
  AppAdminClientsIndexRoute: typeof AppAdminClientsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminClientsClient_idRoute: AppAdminClientsClient_idRoute,
  AppAdminClientsIndexRoute: AppAdminClientsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppUserRouteChildren {
  AppUserProfileRoute: typeof AppUserProfileRoute
}

const AppUserRouteChildren: AppUserRouteChildren = {
  AppUserProfileRoute: AppUserProfileRoute,
}

const AppUserRouteWithChildren =
  AppUserRoute._addFileChildren(AppUserRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppUserRoute: typeof AppUserRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppOrganizationRoute: AppOrganizationRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppUserRoute: AppUserRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSigninRoute: AuthSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
