/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserMycompanyRouteImport } from './routes/user/mycompany'
import { Route as CompanyCompanyIdRouteImport } from './routes/company/$companyId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCompleteAccountRouteImport } from './routes/auth/complete-account'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as CompanyCompanyIdIndexRouteImport } from './routes/company/$companyId/index'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as CompanyCompanyIdTeamRouteImport } from './routes/company/$companyId/team'
import { Route as CompanyCompanyIdScheduleRouteImport } from './routes/company/$companyId/schedule'
import { Route as CompanyCompanyIdAdAccountsRouteImport } from './routes/company/$companyId/ad-accounts'
import { Route as AdminClientsClient_idRouteImport } from './routes/admin/clients/$client_id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserMycompanyRoute = UserMycompanyRouteImport.update({
  id: '/user/mycompany',
  path: '/user/mycompany',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/auth/complete-account',
  path: '/auth/complete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const CompanyCompanyIdIndexRoute = CompanyCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyCompanyIdRoute,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const CompanyCompanyIdTeamRoute = CompanyCompanyIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CompanyCompanyIdRoute,
} as any)
const CompanyCompanyIdScheduleRoute =
  CompanyCompanyIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)
const CompanyCompanyIdAdAccountsRoute =
  CompanyCompanyIdAdAccountsRouteImport.update({
    id: '/ad-accounts',
    path: '/ad-accounts',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)
const AdminClientsClient_idRoute = AdminClientsClient_idRouteImport.update({
  id: '/clients/$client_id',
  path: '/clients/$client_id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/user/mycompany': typeof UserMycompanyRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/clients/$client_id': typeof AdminClientsClient_idRoute
  '/company/$companyId/ad-accounts': typeof CompanyCompanyIdAdAccountsRoute
  '/company/$companyId/schedule': typeof CompanyCompanyIdScheduleRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/company/$companyId/': typeof CompanyCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/user/mycompany': typeof UserMycompanyRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/clients/$client_id': typeof AdminClientsClient_idRoute
  '/company/$companyId/ad-accounts': typeof CompanyCompanyIdAdAccountsRoute
  '/company/$companyId/schedule': typeof CompanyCompanyIdScheduleRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/company/$companyId': typeof CompanyCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/complete-account': typeof AuthCompleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signin': typeof AuthSigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/user/mycompany': typeof UserMycompanyRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/clients/$client_id': typeof AdminClientsClient_idRoute
  '/company/$companyId/ad-accounts': typeof CompanyCompanyIdAdAccountsRoute
  '/company/$companyId/schedule': typeof CompanyCompanyIdScheduleRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/company/$companyId/': typeof CompanyCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/company/$companyId'
    | '/user/mycompany'
    | '/user/profile'
    | '/admin/clients/$client_id'
    | '/company/$companyId/ad-accounts'
    | '/company/$companyId/schedule'
    | '/company/$companyId/team'
    | '/admin/clients/'
    | '/admin/projects/'
    | '/admin/team/'
    | '/company/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/user/mycompany'
    | '/user/profile'
    | '/admin/clients/$client_id'
    | '/company/$companyId/ad-accounts'
    | '/company/$companyId/schedule'
    | '/company/$companyId/team'
    | '/admin/clients'
    | '/admin/projects'
    | '/admin/team'
    | '/company/$companyId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/auth/complete-account'
    | '/auth/forgot-password'
    | '/auth/logout'
    | '/auth/signin'
    | '/company/$companyId'
    | '/user/mycompany'
    | '/user/profile'
    | '/admin/clients/$client_id'
    | '/company/$companyId/ad-accounts'
    | '/company/$companyId/schedule'
    | '/company/$companyId/team'
    | '/admin/clients/'
    | '/admin/projects/'
    | '/admin/team/'
    | '/company/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSigninRoute: typeof AuthSigninRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRouteWithChildren
  UserMycompanyRoute: typeof UserMycompanyRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/mycompany': {
      id: '/user/mycompany'
      path: '/user/mycompany'
      fullPath: '/user/mycompany'
      preLoaderRoute: typeof UserMycompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-account': {
      id: '/auth/complete-account'
      path: '/auth/complete-account'
      fullPath: '/auth/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/company/$companyId/': {
      id: '/company/$companyId/'
      path: '/'
      fullPath: '/company/$companyId/'
      preLoaderRoute: typeof CompanyCompanyIdIndexRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/team'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/company/$companyId/team': {
      id: '/company/$companyId/team'
      path: '/team'
      fullPath: '/company/$companyId/team'
      preLoaderRoute: typeof CompanyCompanyIdTeamRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/schedule': {
      id: '/company/$companyId/schedule'
      path: '/schedule'
      fullPath: '/company/$companyId/schedule'
      preLoaderRoute: typeof CompanyCompanyIdScheduleRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/company/$companyId/ad-accounts': {
      id: '/company/$companyId/ad-accounts'
      path: '/ad-accounts'
      fullPath: '/company/$companyId/ad-accounts'
      preLoaderRoute: typeof CompanyCompanyIdAdAccountsRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
    '/admin/clients/$client_id': {
      id: '/admin/clients/$client_id'
      path: '/clients/$client_id'
      fullPath: '/admin/clients/$client_id'
      preLoaderRoute: typeof AdminClientsClient_idRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminClientsClient_idRoute: typeof AdminClientsClient_idRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminClientsClient_idRoute: AdminClientsClient_idRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompanyCompanyIdRouteChildren {
  CompanyCompanyIdAdAccountsRoute: typeof CompanyCompanyIdAdAccountsRoute
  CompanyCompanyIdScheduleRoute: typeof CompanyCompanyIdScheduleRoute
  CompanyCompanyIdTeamRoute: typeof CompanyCompanyIdTeamRoute
  CompanyCompanyIdIndexRoute: typeof CompanyCompanyIdIndexRoute
}

const CompanyCompanyIdRouteChildren: CompanyCompanyIdRouteChildren = {
  CompanyCompanyIdAdAccountsRoute: CompanyCompanyIdAdAccountsRoute,
  CompanyCompanyIdScheduleRoute: CompanyCompanyIdScheduleRoute,
  CompanyCompanyIdTeamRoute: CompanyCompanyIdTeamRoute,
  CompanyCompanyIdIndexRoute: CompanyCompanyIdIndexRoute,
}

const CompanyCompanyIdRouteWithChildren =
  CompanyCompanyIdRoute._addFileChildren(CompanyCompanyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSigninRoute: AuthSigninRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRouteWithChildren,
  UserMycompanyRoute: UserMycompanyRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
